version: '3.3'

services:
  frontend:
    container_name: poc-dx-nest
    image: poc-dx-nest:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROXY=${DOCKER_PROXY}
    ports:
      - ${DOCKER_EXPOSE_PORT}:80
    restart: always
